version: "3.3"

networks:
  host:
services:
  prometheus:
    image: prom/prometheus
    volumes:
       - ./prometheus/:/etc/prometheus/
    command:
       - --config.file=/etc/prometheus/prometheus.yml
       - --storage.tsdb.path=/prometheus
       - --web.console.libraries=/usr/share/prometheus/console_libraries
       - --web.console.templates=/usr/share/prometheus/consoles
    ports:
       - 9090:9090
    networks: 
       - host
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
       - prometheus
    volumes:
       - ./grafana/:/etc/grafana/
    ports:
       - 3000:3000
    networks: 
       - host
    restart: always
