global:  
  scrape_interval:     5s
  evaluation_interval: 5s
 
scrape_configs:  
  - job_name: 'todo-app'

    metrics_path: '/actuator/prometheus'
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8080']

